# Generated by Django 3.0.5 on 2020-05-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200519_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
